Adds sdcore-gui rock
canonical/sdcore-gui pull request #9
Opened 2023-06-19 21:37 UTC by sanchezfdezjavier

# Initial GUI POC
 This PR includes the first working version of the SD-Core GUI for configuring the network and doing basic CRUD operations with subscribers.

⚠️ Currently, there are important features not included in the scope of this PR:
- Form validation
- Pop-up confirmation dialogs for deleting subscribers and the initial network configuration.
- Handling API is unavailable when loading subscribers, right now it gets stuck in a loading state indefinitely.
- Styling is poor

## Try it out!

The tested setup is:

### 1. Deploy SD-Core

Deploy SD-Core in an AWS EC2 instance and make sure `webui` is up and running.

### 2. Expose the `webui` API endpoint

**2.1. Spin up an Nginx reverse proxy in the AWS instance.**

```bash
sudo apt update -y && sudo apt install nginx
```

**2.2 Configure the reverse proxy by creating an Nginx configuration file**

```bash
ubuntu@ip-172-31-47-116:~/sdcore-gui$ cat /etc/nginx/sites-enabled/webui-proxy 
server {
    listen 8543;

    location / {
        proxy_pass http://<webui service cluster IP>:5000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**2.3 Delete default Ngnix config file.**

Delete all files under `/etc/nginx/sites-enabled` **EXCEPT** from the one created in the previous step.

⚠️ Make sure you replace the webui service cluster IP.

**2.4 Restart Nginx service**

```bash
sudo systemctl restart nginx
```
**2.5 Check you're able to curl the API by making the following request from your local client.**

```bash
curl <EC2 instance public IP>:8543/api/subscriber
```
Example successful API call (If you have no subscribers)

```bash
❯ curl 3.90.228.4:8543/api/subscriber -v
*   Trying 3.90.228.4:8543...
* Connected to 3.90.228.4 (3.90.228.4) port 8543 (#0)
> GET /api/subscriber HTTP/1.1
> Host: 3.90.228.4:8543
> User-Agent: curl/7.84.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.18.0 (Ubuntu)
< Date: Mon, 19 Jun 2023 21:15:51 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 295
< Connection: keep-alive
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With
< Access-Control-Allow-Methods: POST, OPTIONS, GET, PUT, PATCH, DELETE
< Access-Control-Allow-Origin: *
<
* Connection #0 to host 3.90.228.4 left intact
[{"plmnID":"20893","ueId":"imsi-208930100007490"},{"plmnID":"20893","ueId":"imsi-208930100007487"},{"plmnID":"20893","ueId":"imsi-208930100007491"},{"plmnID":"20893","ueId":"imsi-208930100007480"},{"plmnID":"20893","ueId":"imsi-208930100007481"},{"plmnID":"20893","ueId":"imsi-208930100007431"}]
```
If you have no subscribers the array would be empty.

⚠️ Make sure you have the inbound and outbound rules of your Security Group to allow traffic.

## 3. Start the development server

**3.1. Clone SD-Core GUI**

```bash
git clone git@github.com:canonical/sdcore-gui.git && cd sdcore-gui
```

3.2 Install dependencies

```bash
npm install
```

⚠️ You need Node 18, if you have older versions it's probable it won't work.

**3.3. Setup your API endpoint**

Go to `sdcoreConfig.ts` and set the public IP address of the EC2 instance when the `webui` is running on
```Typescript
// SD-Core Webui configuration file.

// The endpoint for the SD-Core Webui API service.
export const WEBUI_ENDPOINT: string = "http://<EC2 public IP address>:8543";

... 
Rest of the file
...
```

**3.4. Start the development server**

```bash
npm run dev
```

You should see something like this
```
> sdcore-gui@0.1.0 dev
> next dev -p 3005

- ready started server on 0.0.0.0:3005, url: http://localhost:3005
- event compiled client and server successfully in 1141 ms (306 modules)
- wait compiling...
- event compiled client and server successfully in 175 ms (306 modules)
- wait compiling /page (client and server)...
- event compiled client and server successfully in 4.6s (884 modules)
- wait compiling...
- event compiled successfully in 1904 ms (482 modules)
``` 

Go to `http://localhost:3005` and start trying out the UI!

<img width="1399" alt="Screenshot 2023-06-19 at 22 57 48" src="https://github.com/canonical/sdcore-gui/assets/32944505/d8dc756e-82ab-4d98-ab7a-a7489188474a">
<img width="1484" alt="Screenshot 2023-06-19 at 22 58 04" src="https://github.com/canonical/sdcore-gui/assets/32944505/d85046ab-1772-44e2-a12a-566a9d082a7f">

2023-06-20 05:48 UTC, saltiyazan commented
I think the title of the PR is not very accurate :)

2023-06-20 07:30 UTC, saltiyazan commented on README.md
Is the `Proof of Concept` warning needed?

2023-06-20 07:32 UTC, saltiyazan commented on README.md
> +rockcraft pack
where is the rockcraft.yaml that is being packed?

2023-06-20 07:38 UTC, saltiyazan commented on package.json
> +    "dev": "next dev -p 3005",
why do we specify the port here?

2023-06-20 08:17 UTC, saltiyazan commented on components/CreateSubscriberButton.tsx
Oh, I see you mentioned in that the for validation is not yet included, in that case please ignore this comment.

2023-06-20 11:46 UTC, gruyaume requested changes

2023-06-20 11:46 UTC, gruyaume commented on .gitignore
We should probably add some github actions. Right now there is nothing that is automatically validated (lint, can build, tests, ...)

2023-06-20 11:46 UTC, gruyaume commented on README.md
> +sudo snap install rockcraft --channel=latest/edge --classic
Probably bundle all the installs at first (rockcraft, skopeo, docker)

2023-06-20 11:46 UTC, gruyaume commented on README.md
> +### 🪨 Rock Container Image
Most of the stuff here should be in a CONTRIBUTING.md, not really in the README

2023-06-20 11:46 UTC, gruyaume commented on sdcoreConfig.ts
> +  "site-info": "demo",
The content here should come from a yaml config file (ex. `config.yaml`)

2023-06-20 11:46 UTC, gruyaume commented on components/NetworkConfiguration.tsx
> +    const data = {
The content here should come from the ocntent in the config file (slice ID, UPF name, upf port, etc.)

2023-06-20 15:31 UTC, gruyaume requested changes

2023-06-20 15:31 UTC, gruyaume commented on .gitignore
For the "can build" part, I guess we can wait to have the rock since it will be built in this context. But for the tests, linting I'm sure we could have at least something rather than nothing.

2023-06-20 15:31 UTC, gruyaume commented on components/DeleteSubscriberButton.tsx
> +          `${WEBUI_ENDPOINT}/config/v1/device-group/cows`,
"cows" souldn't be hardcoded here, it should come from our configuration file

2023-06-20 15:39 UTC, gruyaume commented on sdcoreConfig.ts
> +  "site-info": "demo",
In the future, the charm code will have to generate such configuration file based on config and relations

2023-06-20 15:40 UTC, gruyaume requested changes

2023-06-20 15:40 UTC, gruyaume commented on components/NetworkConfiguration.tsx
> +    const url = `${WEBUI_ENDPOINT}/config/v1/network-slice/default`;
`default` should not be hardcoded at this place.

2023-06-20 17:30 UTC, sanchezfdezjavier commented on package.json
> +    "dev": "next dev -p 3005",
That command is used to start a development server. This is helpful when you are developing concurrently on two platforms, within a container environment, like a Kubernetes cluster, and on a local project (let's say, a repository you've cloned from GitHub).

By default, this server listens on port `3000`. If we do not assign different ports to the container and the local development server, there would be a port conflict because both would be trying to use the same port. To avoid this, we set up the container on port `3000` and the development server on port `3005`.

While I understand that you can easily assign ports in Docker using the 'docker run -it <port>:<targetPort> ...' command and similar in Kubernetes, setting the ports this way helps to avoid any confusion. This ensures that it's clear which service is running on which port, which simplifies the development and debugging process.

Does that make sense?

2023-06-20 17:33 UTC, sanchezfdezjavier commented
> I think the title of the PR is not very accurate :)
Changed. I've should have the title cached somehow.

2023-06-20 20:32 UTC, sanchezfdezjavier commented on README.md
Removed.

2023-06-20 20:33 UTC, sanchezfdezjavier commented on README.md
> +rockcraft pack
I've removed this part. I'll add it in the next PR for the Rock.

2023-06-20 20:33 UTC, sanchezfdezjavier commented on README.md
> +### 🪨 Rock Container Image
I've removed the ROCK part, this will be added in the ROCK PR. I've moved the rest to CONTRIBUTING.md

2023-06-20 20:37 UTC, sanchezfdezjavier commented on README.md
> +sudo snap install rockcraft --channel=latest/edge --classic
I've removed, the ROCK part, it will be added in his PR.

2023-06-20 20:51 UTC, sanchezfdezjavier commented on .gitignore
I've added lint checks as well as the "can build" as a minimal "unit test". I'll add the ROCK test in the corresponding PR.

2023-06-21 07:27 UTC, saltiyazan commented on package.json
> +    "dev": "next dev -p 3005",
Thanks for the explanation.

2023-06-21 10:36 UTC, sanchezfdezjavier commented on sdcoreConfig.ts
> +  "site-info": "demo",
I agree. Probably we want to follow the same approach as in the [juju-dashboard-charm](https://github.com/canonical/juju-dashboard-charm/tree/main/k8s-charm), having the `config.yaml` in the charm and a Jinja template for generating this `sdcoreConfig.ts` file. The problem with directly loading the config from a YAML file resides in the fact that we don't have access to the server file system from the client code, so we can't do something like this:

```javascript
const yaml = require('js-yaml');
const fs   = require('fs');

// Get document, or throw exception on error
try {
  const doc = yaml.load(fs.readFileSync('/home/ixti/example.yml', 'utf8'));
  console.log(doc);
} catch (e) {
  console.log(e);
}
```

So the charm will grab the config from the `config.yaml` render this `sdcoreConfig.ts` from a `sdcoreConfig.ts.j2` template and directly push it to the workload container under the `public` directory. Does that make sense? If it does I believe this will need to come in the charm PR, as all this logic will be handled charm-side.

Let me know what you think.

2023-06-21 12:13 UTC, sanchezfdezjavier commented on components/NetworkConfiguration.tsx
> +    const data = {
Agree, changed.

2023-06-21 12:14 UTC, sanchezfdezjavier commented on components/NetworkConfiguration.tsx
> +    const data = {
Done.

2023-06-21 12:14 UTC, sanchezfdezjavier commented on components/DeleteSubscriberButton.tsx
> +          `${WEBUI_ENDPOINT}/config/v1/device-group/cows`,
Parametrized.

2023-06-21 12:14 UTC, sanchezfdezjavier commented on components/NetworkConfiguration.tsx
> +    const url = `${WEBUI_ENDPOINT}/config/v1/network-slice/default`;
Fixed.

2023-06-21 14:39 UTC, gruyaume requested changes

2023-06-21 14:39 UTC, gruyaume commented on .github/workflows/unit-test.yaml
> +        run: npm run build
The fact that we can build the project is not a "unit" test.

2023-06-21 14:39 UTC, gruyaume commented on public/sdcoreConfig.ts
> +    sst: "1",
Why is there no quotes to `sst`?

2023-06-21 14:39 UTC, gruyaume commented on public/sdcoreConfig.ts
> +    sst: "1",
The same applies at multiple places within the file

2023-06-21 14:39 UTC, gruyaume commented on public/sdcoreConfig.ts
> +    sst: "1",
`sst` is an int, not a string

2023-06-21 14:40 UTC, gruyaume commented on .gitignore
I added another comment on this but the fact that the code builds is not a unit test, that's a "build" step.

2023-06-21 14:44 UTC, gruyaume requested changes

2023-06-21 14:44 UTC, gruyaume commented on README.md
>  Graphical User Interface (GUI) for operating the core (creating subscribers, network slices, device groups).
```suggestion
Graphical User Interface (GUI) for configuring SD-Core and managing subscribers.
```

2023-06-21 15:20 UTC, sanchezfdezjavier commented on public/sdcoreConfig.ts
> +    sst: "1",
Because of the hyphens in the keys. In Javascript, hyphens are not allowed in keys if we don't use the quote notation.

2023-06-22 07:34 UTC, sanchezfdezjavier commented on public/sdcoreConfig.ts
> +    sst: "1",
In the [official documentation](https://docs.sd-core.opennetworking.org/master/configuration/config_rest.html#network-slice-configuration) and in the [tutorial](https://canonical-charmed-5g.readthedocs-hosted.com/en/latest/tutorial/03_configure_sdcore/) it shows as a string. The `tac` is an integer for instance. I'm not getting it.

2023-06-22 07:58 UTC, sanchezfdezjavier commented on README.md
>  Graphical User Interface (GUI) for operating the core (creating subscribers, network slices, device groups).
Changed.

2023-06-22 07:58 UTC, sanchezfdezjavier commented on .github/workflows/unit-test.yaml
> +        run: npm run build
Fixed.

2023-06-22 07:59 UTC, sanchezfdezjavier commented on .gitignore
Addressed.

2023-06-22 13:22 UTC, gruyaume commented on public/sdcoreConfig.ts
> +    sst: "1",
Maybe in the request body the webui expects a string and we would have to translate the int to a string before making the request. But my point is that `sst` is an int, not a string. 

You can look at 3gpp refs on this 
- https://www.etsi.org/deliver/etsi_ts/129500_129599/129571/16.07.00_60/ts_129571v160700p.pdf (page 43)

2023-06-26 09:51 UTC, sanchezfdezjavier commented on public/sdcoreConfig.ts
> +    sst: "1",
I've changed/decided the following for consistency and being 3GPP compliant:
- Changed `sst` from `string` to `number`.
- Kept `sd` as a `string`.
- Changed `tac` from `number` to `string`.

2023-06-27 07:41 UTC, saltiyazan approved these changes

2023-06-27 11:08 UTC, gruyaume approved these changes

2023-06-27 11:12 UTC, merged